version: '2.1'

services:
  # https://github.com/oliver006/redis_exporter
  redisexporter:
    image: oliver006/redis_exporter
    container_name: redisexporter
    restart: unless-stopped
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"

  # https://github.com/lovoo/nsq_exporter
  nsqexporter:
    image: lovoo/nsq_exporter:latest
    container_name: nsqexporter
    ports:
      - "9117:9117"
    command:
      - '-nsqd.addr=http://127.0.0.1:4151'
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v1.3.0
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.43.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    command:
      - '-port=9338'
    restart: unless-stopped
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
